apiVersion: v1
kind: Service
metadata:
  name: agraph
spec:
  selector:
    app: agraph
  type: LoadBalancer
  ports:
  - port: 10035
    name: http
  - port: 10036
    name: https
  externalIPs:
  - ...
