apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
   name: agraph-deployment
   labels:
      app: agraph
spec:
   replicas: 1
   selector:
      matchLabels:
         app: agraph
   template:
      metadata:
         labels:
            app: agraph
      spec:
         volumes:
         - name: dshm
           emptyDir:
             medium: Memory
         - name: data
           persistentVolumeClaim:
             claimName: agraph-storage-1
         containers:
         - name: agraph
           image: alexmilowski/allegrograph-kubernetes:latest
           volumeMounts:
           - name: dshm
             mountPath: /dev/shm
           - name: data
             mountPath: /data
           ports:
           - containerPort: 10035
             name: agraph-http
           - containerPort: 10036
             name: agraph-https
